title: MengXuan Tong's Homepage
page-top-title: MengXuan Tong
top-section-bg-text: Machine Design
home-subtitle: MengXuan Tong&ensp;|&ensp;同孟轩
copyright-text: '&copy; MengXuan Tong 2026. All Rights Reserved.'
